## Модуль Numpy: практическое занятие

In [1]:
import numpy as np

#### Задача 1. Базовое создание массивов
1. Создайте одномерный массив из чисел от 1 до 5.

2. Выведите массив и его тип (dtype).

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Массив:", arr)
print("Тип данных:", arr.dtype)


In [2]:
# функция, которая создаёт массив равномерно распределённых чисел в заданном интервале
a = np.linspace(1, 10, 9)
print(a)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


#### Задача 2. Создание специальных массивов
1. Создайте массив нулей размером 3×3.

2. здайте массив единиц размером 2×4.

3. Создайте массив из 10 равномерно распределённых чисел от 0 до 1 с помощью np.linspace().

4. Выведите форму каждого массива (shape).

In [ ]:
zeros_arr = np.zeros((3, 3))
ones_arr = np.ones((2, 4))
linspace_arr = np.linspace(0, 1, 10)

print("Массив нулей:\n", zeros_arr)
print("Форма:", zeros_arr.shape)
print("\nМассив единиц:\n", ones_arr)
print("Форма:", ones_arr.shape)
print("\nЛинейно распределённые числа:\n", linspace_arr)
print("Форма:", linspace_arr.shape)


#### Задача 3. Арифметические операции
1. Создайте два массива 3×3 со случайными числами (np.random.rand()).

2. Сложите их поэлементно.

3. Умножьте первый массив на 10.

4. Найдите квадратный корень из второго массива.

In [ ]:
arr1 = np.random.rand(3, 3)
arr2 = np.random.rand(3, 3)

sum_arr = arr1 + arr2
multiplied_arr = arr1 * 10
sqrt_arr = np.sqrt(arr2)

print("Первый массив:\n", arr1)
print("Второй массив:\n", arr2)
print("Сумма массивов:\n", sum_arr)
print("Первый массив × 10:\n", multiplied_arr)
print("Квадратный корень из второго массива:\n", sqrt_arr)


Первый массив:
 [[0.52904361 0.65820488 0.75952493]
 [0.23281257 0.68459773 0.05110004]
 [0.01658405 0.66682554 0.17768043]]
Второй массив:
 [[0.81157617 0.15533971 0.13043803]
 [0.07606301 0.37652349 0.75378232]
 [0.02056742 0.25886633 0.10687765]]
Сумма массивов:
 [[1.34061978 0.81354459 0.88996296]
 [0.30887559 1.06112122 0.80488236]
 [0.03715148 0.92569187 0.28455809]]
Первый массив × 10:
 [[5.29043614 6.58204877 7.59524927]
 [2.32812574 6.8459773  0.51100042]
 [0.16584054 6.66825538 1.77680434]]
Квадратный корень из второго массива:
 [[0.90087522 0.39413159 0.36116206]
 [0.27579524 0.6136151  0.86820638]
 [0.14341347 0.50878908 0.32692148]]


#### Задача 4. Агрегатные функции 
Создайте массив 4×4 со случайными числами.

Найдите:

* сумму всех элементов;

* среднее значение;

* максимальное и минимальное значение;

* сумму по строкам;

* сумму по столбцам.

In [ ]:
arr = np.random.rand(4, 4)

total_sum = np.sum(arr)
mean_val = np.mean(arr)
max_val = np.max(arr)
min_val = np.min(arr)
sum_rows = np.sum(arr, axis=1)
sum_cols = np.sum(arr, axis=0)

print("Исходный массив:\n", arr)
print(f"Сумма всех элементов: {total_sum}")
print(f"Среднее значение: {mean_val}")
print(f"Максимальное значение: {max_val}")
print(f"Минимальное значение: {min_val}")
print("Сумма по строкам:", sum_rows)
print("Сумма по столбцам:", sum_cols)


Исходный массив:
 [[0.87556293 0.4560339  0.7392225  0.89684097]
 [0.0527908  0.09396105 0.22793051 0.69629995]
 [0.85871818 0.99332974 0.63726248 0.11135513]
 [0.01238308 0.1309298  0.59565285 0.76446172]]
Сумма всех элементов: 8.142735593632452
Среднее значение: 0.5089209746020282
Максимальное значение: 0.9933297406817619
Минимальное значение: 0.012383080732065177
Сумма по строкам: [2.9676603  1.07098231 2.60066553 1.50342746]
Сумма по столбцам: [1.79945499 1.6742545  2.20006833 2.46895777]


Представьте, что у вас есть данные о температуре в городе за месяц (30 дней). Выполните следующие действия:

1. Создайте массив из 30 случайных чисел в диапазоне 15–30 °C (имитация температур).

2. Найдите среднюю температуру за месяц.

3. Найдите максимальную и минимальную температуру.

4. Определите, сколько дней температура была выше средней.

5. Замените все значения ниже 20 °C на 20 (предположим, это порог комфорта).

6. Выведите все результаты с пояснениями.

In [ ]:
# 1. Создаём массив температур
temperatures = np.random.uniform(15, 30, 30)
temperatures = np.round(temperatures, 1)  # Округляем до 1 знака после запятой

# 2. Средняя температура
avg_temp = np.mean(temperatures)

# 3. Макс. и мин. температура
max_temp = np.max(temperatures)
min_temp = np.min(temperatures)

# 4. Дни выше средней температуры
days_above_avg = np.sum(temperatures > avg_temp)

# 5. Замена температур ниже 20 °C
temperatures[temperatures < 20] = 20

# 6. Вывод результатов
print("Температуры за месяц (°C):", temperatures)
print(f"Средняя температура: {avg_temp:.1f} °C")
print(f"Максимальная температура: {max_temp:.1f} °C")
print(f"Минимальная температура: {min_temp:.1f} °C")
print(f"Дней с температурой выше средней: {days_above_avg}")
print("Температуры после замены (<20 °C → 20 °C):", temperatures)


Температуры за месяц (°C): [22.  21.3 29.  20.  20.  22.9 20.  28.1 20.  20.  28.4 20.4 20.  27.
 23.9 26.9 23.  20.  21.  27.8 20.  21.8 21.3 21.1 20.  26.  20.  20.
 22.5 20. ]
Средняя температура: 21.8 °C
Максимальная температура: 29.0 °C
Минимальная температура: 15.4 °C
Дней с температурой выше средней: 12
Температуры после замены (<20 °C → 20 °C): [22.  21.3 29.  20.  20.  22.9 20.  28.1 20.  20.  28.4 20.4 20.  27.
 23.9 26.9 23.  20.  21.  27.8 20.  21.8 21.3 21.1 20.  26.  20.  20.
 22.5 20. ]


#### Задача 5. Анализ успеваемости студентов
Представьте, что вы анализируете результаты экзаменационной сессии для группы из 25 студентов по трём предметам: математике, физике и программированию. Выполните следующие действия:

1. Создайте двумерный массив размером 25×3, заполненный случайными оценками от 2 до 5 (включительно). Каждая строка — это оценки одного студента, столбцы соответствуют предметам: математика, физика, программирование.

2. Рассчитайте средний балл каждого студента (по трём предметам) и добавьте эти значения в виде четвёртого столбца массива.

3. Найдите:

    * средний балл по каждому предмету (среднее по столбцам);

    * максимальную и минимальную оценку по каждому предмету;

    * количество студентов, получивших «5» по математике;

    * количество студентов, у которых средний балл ≥ 4.

4. Выделите «отличников» — студентов со средним баллом 4.5 и выше. Создайте отдельный массив с их оценками и средними баллами.

5. Для всего массива оценок (без учёта средних баллов) определите:

    * процент оценок «5»;

    * процент оценок «3» и «2» (неудовлетворительные оценки).

6. Выведите все результаты с понятными пояснениями.

In [6]:
# 1. Создаём массив оценок (25 студентов × 3 предмета)
np.random.seed(42)  # для воспроизводимости результатов
grades = np.random.randint(2, 6, size=(25, 3))  # оценки от 2 до 5
subjects = ['Математика', 'Физика', 'Программирование']

print("Оценки студентов (25×3):")
for i, student_grades in enumerate(grades):
    print(f"Студент {i+1}: {student_grades}")

# 2. Рассчитываем средний балл для каждого студента
average_scores = np.mean(grades, axis=1, keepdims=True)  # среднее по строкам
full_data = np.hstack([grades, average_scores])  # добавляем столбец средних баллов

print(f"\nСредний балл каждого студента: {average_scores.flatten()}")

# 3. Анализируем данные по предметам
avg_per_subject = np.mean(grades, axis=0)  # среднее по столбцам
max_per_subject = np.max(grades, axis=0)
min_per_subject = np.min(grades, axis=0)

count_fives_math = np.sum(grades[:, 0] == 5)  # студенты с «5» по математике
count_high_avg = np.sum(average_scores >= 4)  # студенты со средним ≥ 4

print("\nАнализ по предметам:")
for i, subject in enumerate(subjects):
    print(f"{subject}:")
    print(f"  Средний балл: {avg_per_subject[i]:.2f}")
    print(f"  Максимальная оценка: {max_per_subject[i]}")
    print(f"  Минимальная оценка: {min_per_subject[i]}")

print(f"\nКоличество студентов с «5» по математике: {count_fives_math}")
print(f"Количество студентов со средним баллом ≥ 4: {count_high_avg}")

# 4. Выделяем «отличников» (средний балл ≥ 4.5)
excellent_students = full_data[full_data[:, 3] >= 4.5]
print(f"\nКоличество отличников (средний балл ≥ 4.5): {len(excellent_students)}")
if len(excellent_students) > 0:
    print("Оценки отличников (с средними баллами):")
    for i, row in enumerate(excellent_students):
        print(f"Отличник {i+1}: Математика={row[0]}, Физика={row[1]}, Программирование={row[2]}, Средний={row[3]:.2f}")

# 5. Процентное соотношение оценок
total_grades = grades.size  # общее количество оценок
percent_fives = np.sum(grades == 5) / total_grades * 100
percent_unsatisfactory = np.sum((grades == 2) | (grades == 3)) / total_grades * 100

print(f"\nПроцент оценок «5»: {percent_fives:.1f}%")
print(f"Процент неудовлетворительных оценок («2» и «3»): {percent_unsatisfactory:.1f}%")


Оценки студентов (25×3):
Студент 1: [4 5 2]
Студент 2: [4 4 5]
Студент 3: [2 2 4]
Студент 4: [3 4 4]
Студент 5: [4 4 5]
Студент 6: [2 5 5]
Студент 7: [5 4 3]
Студент 8: [2 3 5]
Студент 9: [5 3 3]
Студент 10: [3 5 5]
Студент 11: [2 2 5]
Студент 12: [3 3 2]
Студент 13: [5 2 2]
Студент 14: [4 4 4]
Студент 15: [3 5 5]
Студент 16: [5 5 4]
Студент 17: [3 3 4]
Студент 18: [3 4 5]
Студент 19: [4 5 5]
Студент 20: [2 4 2]
Студент 21: [4 4 2]
Студент 22: [2 4 3]
Студент 23: [5 2 5]
Студент 24: [3 3 3]
Студент 25: [2 3 2]

Средний балл каждого студента: [3.66666667 4.33333333 2.66666667 3.66666667 4.33333333 4.
 4.         3.33333333 3.66666667 4.33333333 3.         2.66666667
 3.         4.         4.33333333 4.66666667 3.33333333 4.
 4.66666667 2.66666667 3.33333333 3.         4.         3.
 2.33333333]

Анализ по предметам:
Математика:
  Средний балл: 3.36
  Максимальная оценка: 5
  Минимальная оценка: 2
Физика:
  Средний балл: 3.68
  Максимальная оценка: 5
  Минимальная оценка: 2
Программирова

#### Задача 6. И снова API 
Разработать класс на Python, который позволяет пользователю искать книги через [Open Library Search API](https://openlibrary.org/dev/docs/api/search) и просматривать результаты.

Приложение должно:

1. Запрашивать у пользователя поисковый запрос (например, название книги, имя автора).

2. Отправлять запрос к [Open Library Search API](https://openlibrary.org/search.json).

3. Обрабатывать ответ API (JSON) и выводить результаты в удобном для чтения формате, например:

        «Преступление и наказание»
        Автор: Фёдор Михайлович Достоевский
        Год первой публикации: 1866
        Есть полный текст: Да
        ID: OL166894W

4. Обрабатывать возможные ошибки.

5. Давать пользователю возможность:

    * выполнить новый поиск;

    * выйти из программы.

6. Решать следующи задачи на выбор (чем больше-тем лучще): 

    * **Сортировка результатов**. Добавить меню выбора сортировки: по году публикации (новые/старые), по релевантности, по количеству изданий.

    * **Фильтрация по языку**. Запросить у пользователя код языка (например, en, ru) и добавить параметр *lang* в запрос API.

    * **Сохранение избранных**. Позволить пользователю добавлять книги в локальный список «Избранное» (сохранять в файл *JSON*) и просматривать его.

    * **Генерация отчёта**. Вывести статистику по результатам поиска: сколько книг с полным текстом, средний год публикации, топ‑3 автора по количеству книг.

    * **Мини‑игра «Угадай книгу»**. Выбрать случайную книгу из результатов, показать обложку и часть данных (например, год и автора), а пользователь должен угадать название.

In [ ]:
import library

book = library.BookResearcher()
book.run()

Добро пожаловать в Книжного Исследователя!

Выберите действие:
1. Поиск книг
2. Показать избранное
3. Выход
Неверный выбор. Попробуйте снова.

Выберите действие:
1. Поиск книг
2. Показать избранное
3. Выход
Неверный выбор. Попробуйте снова.

Выберите действие:
1. Поиск книг
2. Показать избранное
3. Выход


In [ ]:
import requests
url = "https://openlibrary.org/search.json"
parametrs = {
        'q' : 'Pushkin',
        'sort' : 'old'
}
response = requests.get(url, params=parametrs).json()